// packages/vue-demo/src/app.vue
<template>
  <div class="app">
    <Lightboard :store="store" />
  </div>
</template>

<script>
import createControls from "@lightboard/common/src/create-controls.js"
import { Lightboard, createStore } from "@lightboard/vue"

export default {
  components: {
    Lightboard
  },
  beforeCreate () {
    this.store = createStore()
  },
  mounted () {
    createControls(this.store)
  }
}
</script>

<style lang="less">
@import "~@lightboard/common/styles/app.less";
</style>

// packages/react-demo/src/app.jsx
import createControls from "@lightboard/common/src/create-controls.js"
import { Lightboard, Store } from "@lightboard/react"
import React from "react"
import "@lightboard/common/styles/app.less"

class App extends React.Component {
  constructor(props) {
    super(props)
    this.store = new Store()
  }

  componentDidMount () {
    createControls(this.store)
  }

  render () {
    return (
      <div className="app">
        <Lightboard store={this.store} />
      </div>
    )
  }
}

export default App
